INSERT INTO NOTICES(CODE, TITLE, CONTENT, WRITER) VALUES('1161', 'HI~', '¾È³çÇÏ¼¼¿ä~', 'CHM');

DELETE FROM NOTICES WHERE WRITER = 'CHM';

SELECT * FROM NOTICES;

SELECT count(*) FROM( select ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, NOTICES_VIEW.* from notices_VIEW
WHERE title LIKE '%%') N

SELECT * FROM NOTICEFILES;

SELECT COUNT(*) COUNT FROM( select ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
NOTICES_VIEW.* from notices_VIEW
WHERE TITLE LIKE '%%') N

SELECT * FROM NOTICES;

SELECT TOP 1 * FROM NOTICES WHERE CODE > 1339 ORDER BY REGDATE ASC;

SELECT TOP 1 * FROM NOTICES WHERE CODE < 1339 ORDER BY REGDATE DESC;

int hitUp(String code)
UPDATE NOTICES SET HIT = HIT + 1 WHERE CODE = '1339';

UPDATE NOTICES SET HIT=HIT+1 WHERE CODE= 1399